services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: bimbimbambam
      POSTGRES_PASSWORD: bimbimbambam
      POSTGRES_DB: auth_db
    ports:
      - "8003:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  auth-service:
    build:
      context: .
    ports:
      - "8007:8000"
    depends_on:
      - postgres
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  pgdata:
